import { Urbanist } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";

const urbanist = Urbanist({ subsets: ["latin"] });

export const metadata = {
  title: "VYB Intern Assignment",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`bg-white text-black w-screen h-auto ${urbanist.className} flex flex-col items-center`}
      >
        <Navbar />
        {children}
      </body>
    </html>
  );
}
